@startuml
title カレーライス

|ライス|
|カレー|
|具材|

|カレー|
start 
:具材の準備;

fork
|カレー|

    |ライス|
    :米を洗う;
    :炊飯器に米をセットする;
    :米が炊き上がる;

    |ライス|

|具材|
fork again
:野菜をカットする;
:肉を炒める;
:玉ねぎを炒める;
:人参とジャガイモを入れる;
:水を加えて煮込む;
:カレールーを入れる;
:はちみつを入れて煮込む;

|具材|

|カレー|
end fork
:皿に米とカレーを盛りつける;
:カレーライス[]
|カレー|




@enduml