@startuml
left to right direction

[*] --> メニュー
メニュー --> [*]

メニュー -down-> 今の順番 : 現在の順番を確認する
今の順番 -->メニュー

メニュー --> 予約と確認 : 予約する

メニュー --> あなたの順番 : 登録した順番を確認する
メニュー <-- あなたの順番 

あなたの順番 --> 予約と確認
予約と確認 --> あなたの順番 



@enduml