@startuml
left to right direction
高度情報工学科 "1" --- "*" 学生
会社 ---> 社員: 雇う >
会員リスト -- 会員
注文 <.. 注文管理
note right of 注文管理
  注文管理が注文のメソッドもしくは属性を呼び出している
end note
パソコン *-- ハードディスク
note right of パソコン
  ハードディスクがないと成り立ちません。
end note
note right of 会員リスト
    部分クラスがなくて成り立ちます
end note
@enduml