@startuml 
skinparam classAttributeIconSize 0
' class A <<stereotype>> {}
' class B {
'     - 属性１: int
'     - 属性２: String
' }
' class C {
'     ---
'     + 操作１():void
'     + 操作２():String
' }
' class D {
'     - 属性１: int
'     - 属性２: String
'     ---
'     + 操作１(): void
'     + 操作２():String
' }
class Employee{
    -id : int = 0
    -name : String
    #depertment : String
    /勤続年数 : int
    ---
    +setId(Id:int):void
    +getId():int
    +setName(name:String):void
    +getName():String
    +setDept(Dept:String):void
    +getDept():Strig
}
@enduml