@startuml
|客|
|店員|

|客|
start
:弁当をレジに持っていく;
|客|

    |店員|
    fork
    |店員|


    |店員|
    if (温ますか) is (YES) then
    :弁当を温める;
    else (NO)
    endif   
    |店員|
    |店員|
    :弁当を袋に入れる;
    |店員|
|客|
fork again
:お金を払う;
|客|
|店員|
:精算する;
end fork
|店員|
|客|
:弁当を手に持つ;
|客|
stop

@enduml