@startuml

|販売代理店|
|営業部門|
|製造部門|

|販売代理店|
:発注;
|販売代理店|

    |営業部門|
    :受注;
    :在庫調査;
    if () then (在庫あり)
    :;
    |営業部門|
    
    |製造部門|
    else (在庫なし)
    :製造;
    |製造部門|

    |営業部門|
    endif
    :発送;
    |営業部門|

|販売代理店|
:検収/支払い;
|販売代理店|

    |営業部門|
    :入金確認;
    |営業部門|

    stop
@enduml