@startuml


state 予約システム{
state entry <<entryPoint>>
state exit <<exitPoint>>

entry ->メニュー

メニュー -down-> 予約と確認 : 予約する
メニュー -down-> あなたの順番 : 登録した順番を確認する
メニュー --> 今の順番 : 現在の順番を確認する

予約と確認 --> メニュー : 順番を取消する

予約と確認 --> あなたの順番 : 登録ボタンを押す

今の順番 --> 今の順番 : 患者番号を1つ増やす
メニュー --> exit
}
[*] --> entry
exit -> [*]

@enduml
