@startuml

state 自動販売機 {
    state entry <<entryPoint>>
    state exit <<exitPoint>>

  entry --> お金投入
  お金投入 --> ボタン
  ボタン --> ドリンク提供
  ドリンク提供 --> exit
}
[*] -right-> entry
exit -down-> [*]

@enduml
