@startuml

class ライントレーサー {
  - 光センサー: 光センサー
  - 右モータ: 右モータ
  - 左モータ: 左モータ
  - CPU: CPU
  - 電源SW: 電源SW
  + 電源ON(): void
  + 電源OFF(): void
}

class 光センサー {
  + 判断(): void
}

class 右モータ {
  + ON(): void
  + OFF(): void
}

class 左モータ {
  + ON(): void
  + OFF(): void
}

class CPU {
  
}

class 電源SW {
 
}

ライントレーサー "1" *-- 光センサー : 光センサー制御
ライントレーサー "1" *-- 右モータ : 右モータ制御
ライントレーサー "1" *-- 左モータ : 左モータ制御
ライントレーサー "1" *-- CPU : CPU制御
ライントレーサー "1" *-- 電源SW : システム起動

@enduml
