@startuml
hide footbox
mainframe sd 予約
participant ":データ更新コントローラー" as controller <<control>>
participant ":ホテル" as operation <<hotel>>

    activate controller
        controller -> operation : 予約する()
            activate operation
            create ":予約" as reserve
                operation -> reserve : <<create>>
                   
                operation -> operation : 予約登録()
                    activate operation
                    deactivate operation
            deactivate operation

@enduml