@startuml

|顧客|
|スタッフ|
|厨房|

|スタッフ|
start
:挨拶をする;
:注文を聞く;
|スタッフ|
    |顧客|
    :注文する;
    |顧客|
|スタッフ|
:注文を確認する;
fork
:代金を請求する;
|スタッフ|
    |顧客|
    :代金を払う;
    |顧客|
|スタッフ|
fork again
:商品の調理を依頼する;
|スタッフ|
    |厨房|
    :商品を料理する;
    |厨房|
|スタッフ|
fork end
:テイクアウトかどうか尋ねる;
if () is ([テイクアウト]) then
:袋に入れる;
else ([店内])
:トレイに乗せる;
endif
:商品を渡す;
|スタッフ|
    |顧客|
    :商品を受け取る;
    |顧客|

stop

@enduml