@startuml
class ホテル {
    - 部屋
}

class 部屋 {
    - タイプ
    - 価格
    -  キャンペーン価格
}

class 利用者 {
  - 名前
  - 住所
  - 電話番号
}

class 予約 {
    - チェックイン日
    - 滞在期間
   - 値段
}

ホテル "1" -- "*" 利用者
ホテル "1" *-- "*" 部屋
部屋 "0..*" o-- "1" 予約
利用者  -->  予約

@enduml
