@startuml
left to right direction
class 顧客{
    氏名
    住所
}
class 注文{
    注文日
    数量
}
class 重要顧客{
    氏名 高橋洋平
}
class 商品A{
    商品名 テレビ
    型式 V12345
}
class 商品B{
    商品名 冷蔵庫
    型式 R8765
}
class 商品C{
    商品名 プロジェクタ
    型式 P1122
}

顧客 <|-- 重要顧客
顧客 "1" -- "*" 注文
注文 "*" -- "1" 商品
重要顧客 <-- 商品A
重要顧客 <-- 商品B
@enduml